[package]
name = "hickory"
version = "0.1.0"
edition = "2021"

[dependencies]
hickory-resolver = {version="0.24.2", features=["dns-over-https-rustls", "dns-over-rustls"]}
reqwest = {version="0.12.12"}
once_cell = "1.20.2"
tokio = { version="1.42.0", features=["rt", "macros"] }